- data/guide/plugins/assert.md
- out/guide/plugins/index.html
This reflects chaijs/chai#382.
(Feel free to get rid or ask me to get rid of b79ed48 if it is unnecessary, I admit I haven't investigated too much into your publication process...)
> Update the guide to mention the showDiff argument of assert

- plugins.js
At the time of sending this PR, Chai Immutable is v0.2.1 and will evolve, maybe without keeping BC depending on the feedback I have. But I already saw some people showing interest in the plugin and I figured I should rather share it sooner than later.
Also, I haven't done anything towards browser support yet but it is planned as [Immutable](http://facebook.github.io/immutable-js/) itself has browser support.
Let me know if you have any other quality requirements to follow to get this accepted and I'll do my best to comply with them ASAP.
> Add Chai Immutable in the plugins

- plugins.js
Adds the chai signals plugin to the plugin.js. Chai signals adds assertions for the [js-signals](https://github.com/millermedeiros/js-signals) library.
> Add chai-signals plugin

- plugins.js
Assert on equality of json representations in Chai.
```js
var ship = "ship",
barge = {toJSON: function () {
return "ship";
}}
ship.should.jsonEqual(barge);
```
> Add chai-json-equal plugin

- plugins.js
This is true since version 1.3.0: https://github.com/astorije/chai-immutable/releases/tag/v1.3.0
> Specify that browser is supported for chai-immutable

- plugins.js
I [forked](https://github.com/nathanboktae/chai-dom) `chai-jquery` to work against the vanilla Web API and would like to tell the world about it. Thanks for the awesome assertion library!
> Add chai-dom to the list of plugins

- _legacy_plugins
See https://github.com/astorije/chai-immutable/commit/39540ffc1f4f43f7aa3175eef7a90d59b46665b6
---
Is it enough to add the `chai-plugin` keyword to safely remove this line from the legacy listing?
> Move chai-immutable to the new plugin system

- _guides/helpers.md
`addMethod` docs was missing. Also added note about preferring `overwriteMethod` for sharing method namespaces, as discussed in [#528](https://github.com/chaijs/chai/pull/528#issuecomment-171582002)
> added note about preferring overwriteMethod to addMethod

- data/codex.json
- out/api/assert/index.html
- out/api/bdd/index.html
- out/api/index.html
- out/api/plugins/index.html
- out/api/test/index.html
- out/chai.js
- out/guide/helpers/index.html
- out/guide/index.html
- out/guide/installation/index.html
- out/guide/plugins/index.html
- out/guide/resources/index.html
- out/guide/styles/index.html
- out/index.html
- out/public/js/tests/assert.js
- out/public/js/tests/configuration.js
- out/public/js/tests/expect.js
- out/public/js/tests/should.js
- out/public/js/tests/utilities.js
I saw #74 regarding porting to Jekyll, but unfortunately I don't have time to help out with that right now as I have no familiarity with Jekyll, but I was thinking as a stopgap the current site could be updated for the latest version of Chai. I spent a while banging my head against the wall trying to figure out why my test wasn't working before realizing it was an error in the documentation which had been fixed but not updated on the website.
> Update docs for Chai 3.4.2

- _sass/_main.scss
All the code samples on the home page are in an ugly serifed font for me.
The CSS currently has:
font-family: Monaco, Bitstream Vera Sans Mono, Lucida Console, Terminal;
which means that unless you have one of exactly that set of fonts installed,
you get browser default.
The fix is to add "monospace" to the end of the list.
> use "monospace" as the final fallback code font

- _includes/footer.html
This exposes the `chai` global on every page of the site, allowing people to test things in the dev console.
Being able to easily test a feature while reading its documentation can be very handy, and a few other documentation sites also expose globals for this purpose. ([lodash.com](https://lodash.com) exposes a `_` global, [bluebirdjs.com](http://bluebirdjs.com) exposes a `Promise` global, etc.)
> Expose a chai global for use in the console

- api/test.md
Related to issue #122.
This is to prevent users to scratch their head as to why the tests are not running on their browsers.
It is of course a temporary measure before it gets re-added for real.
> Add a temporary note about the disabled test suite

- _includes/banner.html
Just a small fix for a typo that has been on the front page of the chaijs.com website for a while.
Missing the word "to" as shown by the screen shot:
> Correct typo in banner.html

- Makefile
Since this is the org's main github pages repo, the site is built from `master`, not `gh-pages`.
> Make Travis push _data to master instead of gh-pages

- _includes/head.html
Since github already overwrites `site.url`, we don't need to prepend `site.github.url`.
> **GitHub Pages overrides the "Site Source" configuration value**, so if you locate your files anywhere other than the root directory, your site may not build correctly.
As you can see, before this PR, we have a duplicate url there:
> Fix canonical URL

- _sass/_main.scss
Google Chrome blocks any mixed content requests.
> Change http to https for Google Font URL

- _includes/footer.html
Chai use github actions as CI now, so replace travis-ci link width github actions. cc  @keithamus
> chore: update doc website footer build status link

- _scripts/banned_plugins.js
[`chai-sinon`](https://github.com/michaelgmcd/chai-sinon) is a fork of [`sinon-chai`](https://github.com/domenic/sinon-chai) which intends to be more maintained. However, it hasn't been updated for more than 5 years and has a very low adoption rate ([600 weekly downloads on npm](https://www.npmjs.com/package/chai-sinon) vs [600k for sinon-chai](https://www.npmjs.com/package/sinon-chai)).
> Ban not maintained fork of sinon-chai

- api/plugins.md
Fixed typo cause the [page name](https://github.com/chaijs/chaijs.github.io/blob/master/_guides/plugins.md#core-plugin-concepts) is 'Co**R**e Plugin Concepts'
> Fix type in api/plugins.md

- _guides/index.md
- _guides/using-chai-with-esm-and-plugins.md
This pull request introduces a comprehensive guide on using Chai with ECMAScript Modules (ESM) and plugins, specifically focusing on the chai-http plugin and best practices for plugin authors to expose globals sustainably.
- **Adds a new guide**: A detailed guide titled "Using Chai with ESM and Plugins" is added, covering how to import Chai, use plugins like chai-http, and the nuances of importing vs. using globals across files.
- **Updates the Guide Index**: The `_guides/index.md` file is updated to include a link to the new guide under the "Basics" section, ensuring easy access for users looking to integrate Chai with ESM and plugins.
- **Expands on Making Plugins**: Within the "Making Plugins" section of `_guides/index.md`, a new subsection is introduced, offering guidance to plugin …
> Add guide on using Chai with ESM and plugins

- _scripts/build-plugin-pages.js
Fixes #212. Encodes `@` and `/` characters to ensure valid YAML in markdown files.
> Add encodeURIComponent in md in build-plugin-pages.js

- _guides/helpers.md
- _guides/plugins.md
- _guides/styles.md
- _guides/using-chai-with-esm-and-plugins.md
Updates the guides to use ES module imports and `const` rather than `var`.
cc @koddsson 
Fixes chaijs/chai#1654
Although I've updated the guides here, almost all of the docs in `plugins/` are wrong (CJS). but there's so many, I think we should do a bit at a time and may even be able to remove some of the ancient ones
> docs: update guides to use esm
